language: android

jdk:
- oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra

after_script:
    - cat ./build/outputs/lint-results.xml

sudo: false
